### PR TITLE
redhat-rpm-sign-ostree: Reimplementation of rpm-ostree compose sign

### PR DESCRIPTION
**Pull request by cgwalters**
See https://github.com/projectatomic/rpm-ostree/pull/607

### CODE REVIEW

**Comment by parasense** [comment]
This script generates the following traceback
`Traceback (most recent call last):
  File "/root/redhat-rpm-sign-ostree", line 31, in <module>
    r.open(None)
GLib.Error: g-io-error-quark: Opening objects/ directory: openat: No such file or directory (1)`

**Comment by cgwalters** [comment]
@parasense Does it work for you with the above `fixup!` ⬆️ ?

**Comment by cgwalters** [comment]
(This is a pygobject API difference between Fedora 25+ and RHEL7)

**Review by parasense — APPROVED** [review]
This works. thank you!

**Pull request merged**
